In [2]:
import numpy as np

a = np.array([[0 if (i + j) % 2 == 0 else 1 for j in range(8)] for i in range(8)])
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [12]:
a = np.array([np.arange(5) for i in range(5)])
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [13]:
a = np.random.rand(3, 3, 3)
a

array([[[0.95730167, 0.76659524, 0.4968277 ],
        [0.16649188, 0.63073633, 0.20867118],
        [0.62472358, 0.29759327, 0.46135375]],

       [[0.49096127, 0.80637941, 0.2012615 ],
        [0.3629289 , 0.47395876, 0.16034231],
        [0.27367034, 0.37300808, 0.95099338]],

       [[0.55256948, 0.61828317, 0.15019566],
        [0.11143857, 0.11037943, 0.05452478],
        [0.26028648, 0.64457305, 0.83310159]]])

In [21]:
a = np.array([np.full(5, 1) for i in range(5)])
for i in range(1, 4):
    a[i] = np.array([1, 0, 0, 0, 1])
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [33]:
a = np.random.rand(10)
a = -np.sort(-a)
print(a)

[0.13685323 0.56030688 0.08175474 0.24774581 0.49375552 0.46911208
 0.09223793 0.12057096 0.78330591 0.74800703]
[0.78330591 0.74800703 0.56030688 0.49375552 0.46911208 0.24774581
 0.13685323 0.12057096 0.09223793 0.08175474]


In [8]:
a = np.array([[0 if (i + j) % 2 == 0 else 1 for j in range(8)] for i in range(8)])
print(a.shape) #форма
print(a.size) #размер
print(a.ndim) #число измерений

(8, 8)
64
2


In [2]:
import pandas as pd
import math
first = (5, 10)
second = (11, 19)
s1 = pd.Series(first)
s2 = pd.Series(second)

print(math.sqrt((s1[0] - s2[0])**2 + (s1[1] - s2[1])**2))


10.816653826391969


In [50]:
url = 'https://www.stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2021-financial-year-provisional/Download-data/annual-enterprise-survey-2021-financial-year-provisional-csv.csv'
dataframe = pd.read_csv(url)
dataframe.head(3)

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC  \
0  2021                     Level 1                99999       All industries   
1  2021                     Level 1                99999       All industries   
2  2021                     Level 1                99999       All industries   

                Units Variable_code  \
0  Dollars (millions)           H01   
1  Dollars (millions)           H04   
2  Dollars (millions)           H05   

                                     Variable_name      Variable_category  \
0                                     Total income  Financial performance   
1  Sales, government funding, grants and subsidies  Financial performance   
2                Interest, dividends and donations  Financial performance   

     Value                             Industry_code_ANZSIC06  
0  757,504  ANZSIC06 divisions A-S (excluding classes K633...  
1  674,890  ANZSIC06 divisions A-S (excluding classes K633...  
2   49,593  ANZSIC06 divisions A-S (excluding classes K633...

In [51]:
dataframe.head(4)

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC  \
0  2021                     Level 1                99999       All industries   
1  2021                     Level 1                99999       All industries   
2  2021                     Level 1                99999       All industries   
3  2021                     Level 1                99999       All industries   

                Units Variable_code  \
0  Dollars (millions)           H01   
1  Dollars (millions)           H04   
2  Dollars (millions)           H05   
3  Dollars (millions)           H07   

                                     Variable_name      Variable_category  \
0                                     Total income  Financial performance   
1  Sales, government funding, grants and subsidies  Financial performance   
2                Interest, dividends and donations  Financial performance   
3                             Non-operating income  Financial performance   

     Value                             Industry_code_ANZSIC06  
0  757,504  ANZSIC06 divisions A-S (excluding classes K633...  
1  674,890  ANZSIC06 divisions A-S (excluding classes K633...  
2   49,593  ANZSIC06 divisions A-S (excluding classes K633...  
3   33,020  ANZSIC06 divisions A-S (excluding classes K633...

In [52]:
dataframe.tail(4)

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
41711  2013                     Level 3                 ZZ11   
41712  2013                     Level 3                 ZZ11   
41713  2013                     Level 3                 ZZ11   
41714  2013                     Level 3                 ZZ11   

             Industry_name_NZSIOC       Units Variable_code  \
41711  Food product manufacturing  Percentage           H38   
41712  Food product manufacturing  Percentage           H39   
41713  Food product manufacturing  Percentage           H40   
41714  Food product manufacturing  Percentage           H41   

                             Variable_name Variable_category Value  \
41711  Margin on sales of goods for resale  Financial ratios    40   
41712                     Return on equity  Financial ratios    12   
41713               Return on total assets  Financial ratios     5   
41714                Liabilities structure  Financial ratios    46   

                                  Industry_code_ANZSIC06  
41711  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41712  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41713  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41714  ANZSIC06 groups C111, C112, C113, C114, C115, ...

In [53]:
dataframe.shape

(41715, 10)

In [54]:
dataframe.describe()

Year
count  41715.00000
mean    2017.00000
std        2.58202
min     2013.00000
25%     2015.00000
50%     2017.00000
75%     2019.00000
max     2021.00000

In [55]:
dataframe.iloc[1:5]

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC  \
1  2021                     Level 1                99999       All industries   
2  2021                     Level 1                99999       All industries   
3  2021                     Level 1                99999       All industries   
4  2021                     Level 1                99999       All industries   

                Units Variable_code  \
1  Dollars (millions)           H04   
2  Dollars (millions)           H05   
3  Dollars (millions)           H07   
4  Dollars (millions)           H08   

                                     Variable_name      Variable_category  \
1  Sales, government funding, grants and subsidies  Financial performance   
2                Interest, dividends and donations  Financial performance   
3                             Non-operating income  Financial performance   
4                                Total expenditure  Financial performance   

     Value                             Industry_code_ANZSIC06  
1  674,890  ANZSIC06 divisions A-S (excluding classes K633...  
2   49,593  ANZSIC06 divisions A-S (excluding classes K633...  
3   33,020  ANZSIC06 divisions A-S (excluding classes K633...  
4  654,404  ANZSIC06 divisions A-S (excluding classes K633...

In [59]:
dataframe[dataframe['Year'] == 2015].head(5)

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
27810  2015                     Level 1                99999   
27811  2015                     Level 1                99999   
27812  2015                     Level 1                99999   
27813  2015                     Level 1                99999   
27814  2015                     Level 1                99999   

      Industry_name_NZSIOC               Units Variable_code  \
27810       All industries  Dollars (millions)           H01   
27811       All industries  Dollars (millions)           H04   
27812       All industries  Dollars (millions)           H05   
27813       All industries  Dollars (millions)           H07   
27814       All industries  Dollars (millions)           H08   

                                         Variable_name      Variable_category  \
27810                                     Total income  Financial performance   
27811  Sales, government funding, grants and subsidies  Financial performance   
27812                Interest, dividends and donations  Financial performance   
27813                             Non-operating income  Financial performance   
27814                                Total expenditure  Financial performance   

         Value                             Industry_code_ANZSIC06  
27810  591,538  ANZSIC06 divisions A-S (excluding classes K633...  
27811  517,905  ANZSIC06 divisions A-S (excluding classes K633...  
27812   56,137  ANZSIC06 divisions A-S (excluding classes K633...  
27813   17,495  ANZSIC06 divisions A-S (excluding classes K633...  
27814  527,372  ANZSIC06 divisions A-S (excluding classes K633...

In [3]:
from sklearn import preprocessing
url_new = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
datafremen = pd.read_csv(url_new)
datafremen.head(2)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa

In [7]:
scaler = preprocessing.MinMaxScaler(feature_range = (0, 1))
datafremen[['sepal_length_cm']] = scaler.fit_transform(datafremen[['sepal_length_cm']])
scaler_new = preprocessing.StandardScaler()
datafremen[['sepal_width_cm']] = scaler.fit_transform(datafremen[['sepal_width_cm']])
datafremen

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        0.625000              1.4             0.2   
1           0.166667        0.416667              1.4             0.2   
2           0.111111        0.500000              1.3             0.2   
3           0.083333        0.458333              1.5             0.2   
4           0.194444        0.666667              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667        0.416667              5.2             2.3   
146         0.555556        0.208333              5.0             1.9   
147         0.611111        0.416667              5.2             2.0   
148         0.527778        0.583333              5.4             2.3   
149         0.444444        0.416667              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]